address/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('address.views',
    url(r'^addresses/$', 'addresses', name='addresses'),
    url(r'^street_names/$', 'street_names', name='street_names'),
)

base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('base.views',
    url(r'^flatpages/(?P<slug>.*)/$', 'flat_page', name='flat_page'),
)

spbisp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^captcha/', include('captcha.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^admin/address/update_from_csv/',
        'address.views.update_addresses',
        name='update_addresses'
    ),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^providers/', include('providers.urls', namespace='providers')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns+= patterns('base.views',
    url(r'^$', 'index', name='index'),
    url(r'^order/$', 'order', name='order'),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
#coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse

from easy_thumbnails.files import get_thumbnailer
from filer.fields.image import FilerImageField

from ckeditor.fields import RichTextField


class BaseModel(models.Model):
    title = models.CharField(u'Название', max_length=255)
    __unicode__ = lambda self: self.title
    class Meta:
        abstract=True


class FlatPage(BaseModel):
    content = RichTextField(u'Содержание')
    slug = models.SlugField(u'Путь', max_length=255, unique=True,
                help_text=u'Заполнить название'
    )

    class Meta:
        verbose_name= u'простая страница'
        verbose_name_plural = u'простые страницы'

    def get_absolute_url(self):
        return reverse('base:flat_page', kwargs=dict(slug=self.slug))


class SliderItem(models.Model):
    flr_image = FilerImageField(verbose_name=u'Изображение')
    is_active = models.BooleanField(u'Показать на главной', default=True)

    @property
    def image_hd_url(self):
        opts = dict(size=(1920,1080))
        thumbnail = get_thumbnailer(self.flr_image).get_thumbnail(opts)
        return thumbnail.url

    class Meta:
        verbose_name= u'Элемент слайдера'
        verbose_name_plural = u'Элементы слайдера'


class BlockOnSlider(models.Model):
    title = models.CharField(u'Название', max_length=44)
    text = models.TextField(u'Teкст', max_length=185)
    tp = models.PositiveSmallIntegerField(u'Расположение блока', unique=True,
                            choices=(
                                        (0, u'Левый'),
                                        (1, u'Центр'),
                                        (2, u'Правый'),
                            )
    )
    __unicode__ = lambda self: self.title

    class Meta:
        verbose_name= u'Блок на слайдере'
        verbose_name_plural = u'Блоки на слайдере'


class SystemTunes(BaseModel):
    phone = models.CharField(u'Телефон', max_length=255, blank=True)
    email = models.EmailField('email', blank=True)
    is_active = models.BooleanField(u'Активный', default=True)
    sliderspeed = models.PositiveSmallIntegerField(u'Скорость слайдера, сек',
        default=10)
    google_analytics = models.TextField(u'Код Google-аналитики', blank=True)
    yandex_metrics = models.TextField(u'Код Yandex-метрики', blank=True)
    keywords = models.CharField(u'SEO keywords',
                                max_length=2048, blank=True)
    description = models.CharField(u'SEO description',
                                max_length=2048, blank=True)
    class Meta:
        verbose_name= u'Системные настройки'
        verbose_name_plural = verbose_name

    sliderspeedms = property(lambda self: self.sliderspeed*1000)

base/views.py
#coding: utf-8
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import DetailView
from django.views.generic import TemplateView

from address.models import Address
from address.views import Addresses
from providers.models import Provider

from .models import FlatPage


class IndexPage(TemplateView):
    template_name='index.html'

    def get_context_data(self, **kwargs):
        ctx = super(IndexPage, self).get_context_data(**kwargs)
        ctx['providers'] = Provider.objects.all()[:3]
        if self.request.GET:
            ctx['results'] = self.get_addrs()
        return ctx

    def get_addrs(self):
        qs = Address.objects.all()
        qs = Addresses(request=self.request).filter_queryset(qs)
        return qs
index = IndexPage.as_view()


class DetailPage(DetailView):
    template_name = 'object_detail.html'
    context_object_name = 'detail_page'
    model = FlatPage

    def get(self, request, *args, **kwargs):
        if self.get_object():
            return super(DetailPage, self).get(request, *args, **kwargs)
        else:
            return redirect(reverse('index'))
flat_page = DetailPage.as_view()


class OrderPage(TemplateView):
    template_name='order.html'
order = OrderPage.as_view()

base/templates/partial/filters/searchbar.html
<section class="searchBar">
    <div class="contentWrapper">
        <h2>Подключен ли ваш дом</h2>
        <form class="searchForm">
            {% csrf_token%}
            <label>Адрес:</label>
            <input type="text" name="street" value="" placeholder="Введите свою улицу" class="adressMain" required="required">
            <input type="hidden" name="street_pk" value="">
            <input type="text" name="house" value="" placeholder="дом" class="adressHouse" required="required">
            <input type="text" name="housing" value="" placeholder="корпус" class="adressCorp">
            <button class="searchBtn">Проверить</button>
        </form>

        <script type="text/javascript">
        $(document).ready(function() {
            var street_pk = $('form[class=searchForm] input[name=street_pk]');
            var street =  $('form[class=searchForm] input[name=street]');
            var house = $('form[class=searchForm] input[name=house]');
            var housing = $('form[class=searchForm] input[name=housing]');

            street.autocomplete({
              source: function( request, response ) {
                $.ajax({
                    url: '{% url 'address:street_names' %}?title='+request.term,
                    success: function( data ) {
                        response( $.map( data, function( item ) {
                        return {
                            label: item.title,
                            value: item.id,
                        }
                    }));
                    }
                });
              },
            select: function(event, ui) {
                $(this).val(ui.item.label);
                street_pk.val(ui.item.value);
                house.val('');
                housing.val('');
                return false;
            },
              minLength: 3,
            });

            house.autocomplete({
              source: function( request, response ) {
                if (street_pk.val()) {
                    $.ajax({
                        url: '{% url 'address:addresses' %}?houses='+request.term+'&street_pk='+street_pk.val(),
                        success: function( data ) {
                            response( $.map( data, function( item ) {
                                var house = item.house;
                                if (item.housing) {
                                    house = item.house+' к. '+item.housing;
                                }
                            return {
                                label: house,
                                value: item.house,
                                housing: item.housing,
                            }
                        }));
                        }
                    });
                }
              },
            select: function(event, ui) {
                $(this).val(ui.item.value);
                housing.val(ui.item.housing);
                return false;
            },
              minLength: 1,
            });
        });
        </script>
    </div>
</section>