base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('base.views',
    url(r'^flatpages/(?P<slug>.*)/$', 'flat_page', name='flat_page'),
)

providers/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('providers.views',
    url(r'^prvdrs_list/$', 'prvdrs_list', name='prvdrs_list'),
    url(r'^specials/$', 'specials', name='specials'),
)

reviews/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('reviews.views',
    url(r'^review_create/$', 'review_create', name='review_create'),
    url(r'^reviews_list/$', 'reviews_list', name='reviews_list'),
)

spbisp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^captcha/', include('captcha.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^admin/address/update_from_csv/',
        'address.views.update_addresses',
        name='update_addresses'
    ),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^providers/', include('providers.urls', namespace='providers')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns+= patterns('base.views',
    url(r'^$', 'index', name='index'),
    url(r'^order/$', 'order', name='order'),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

providers/models.py
#coding: utf-8
from django.core.urlresolvers import reverse
from django.db import models

from ckeditor.fields import RichTextField
from easy_thumbnails.files import get_thumbnailer
from filer.fields.image import FilerImageField

from base.models import BaseModel

from .choices import SERVICETYPES
from .managers import ProviderManager, SpecialsManager, TariffManager


class ITStandart(BaseModel):
    sorting = models.PositiveIntegerField('Сортировка', default=0)
    class Meta:
        ordering= 'sorting', 'pk',
        verbose_name=u'Стандарт передачи данных'
        verbose_name_plural=u'Стандарты передачи данных'


class Service(BaseModel):
    sorting = models.PositiveIntegerField('Сортировка', default=0)
    tp = models.CharField(u'Тип услуги', default='internet_home.png',
                        choices=SERVICETYPES, max_length=32)
    class Meta:
        ordering= 'sorting', 'pk',
        verbose_name=u'Услуга'
        verbose_name_plural=u'Услуги'


class Tariff(BaseModel):
    objects = TariffManager()
    services = models.ManyToManyField(Service, null=True, blank=True,
                                verbose_name=Service._meta.verbose_name_plural)
    standarts = models.ManyToManyField(ITStandart, null=True, blank=True,
                                verbose_name=ITStandart._meta.verbose_name_plural)
    desc = RichTextField(u'Описание', max_length=4096)
    price = models.CharField(u'Стоимость', max_length=255)
    speed = models.CharField(u'Скорость', blank=True, null=True, max_length=255)
    con_term = models.CharField(u'Срок подключения, дней', blank=True, null=True,
                                max_length=255)
    sorting = models.PositiveIntegerField('Сортировка', default=0)
    class Meta:
        ordering= 'sorting', 'pk',
        verbose_name=u'Тариф'
        verbose_name_plural=u'Тарифы'


class Special(BaseModel):
    objects = SpecialsManager()
    services = models.ManyToManyField(Service, null=True, blank=True,
                                verbose_name=Service._meta.verbose_name_plural)
    desc = RichTextField(u'Описание', max_length=4096)
    start_date = models.DateTimeField(u'Начало', null=True)
    end_date = models.DateTimeField(u'Окончание', null=True)
    sorting = models.PositiveIntegerField('Сортировка', default=0)
    tariffs = models.ForeignKey(Tariff, null=True, blank=True,
                                verbose_name=Tariff._meta.verbose_name)
    class Meta:
        ordering= 'sorting', 'pk',
        verbose_name=u'Акция'
        verbose_name_plural=u'Акции'


class Provider(BaseModel):
    objects= ProviderManager()
    site = models.URLField(u'Cайт', blank=True)
    logo = FilerImageField(verbose_name=u'Логотип', null=True, blank=True)
    desc = RichTextField(u'Описание', max_length=4096, blank=True)
    services = models.ManyToManyField(Service, null=True, blank=True,
                                verbose_name=Service._meta.verbose_name_plural)
    tariffs = models.ManyToManyField(Tariff, null=True, blank=True,
                                verbose_name=Tariff._meta.verbose_name_plural)
    specials = models.ManyToManyField(Special, null=True, blank=True,
                                verbose_name=Special._meta.verbose_name_plural)
    sorting = models.PositiveIntegerField('Сортировка', default=0)
    rating = models.CharField(u'Рейтинг', blank=True, max_length=255)

    class Meta:
        ordering= 'sorting', 'pk',
        verbose_name=u'Провайдер'
        verbose_name_plural=u'Провайдеры'

    @property
    def calculate_rating(self):
        default = '-'
        if self.review_set.exists():
            return self.review_set.actual(
                                ).aggregate(models.Avg('rate')
                                ).get('rate__avg', default)
        return default

    def get_absolute_url(self):
        return reverse('providers:prvdrs_list')+'?pk='+str(self.pk)

    def thumbnail_logo(self, size=None):
        if self.logo and size:
            opts = dict(size=size, crop=True)
            try:
                thumbnail = get_thumbnailer(self.logo).get_thumbnail(opts)
                return thumbnail.url
            except: pass

    @property
    def adaptive_logo_url(self):
        return self.thumbnail_logo(size=(218,145)) or ''

    @property
    def logo_120_url(self):
        return self.thumbnail_logo(size=(120,120)) or ''

providers/views.py
#coding: utf-8
from django.db.models import Q
from django.views.generic import ListView

from .models import Provider, Special


class ProviderList(ListView):
    model = Provider
    template_name = 'providers.html'

    def get_queryset(self):
        qs = super(ProviderList, self).get_queryset()
        #TODO: refact this
        q=Q()
        if self.request.GET:
            body = self.request.GET
            if body.get('pk'):
                q&=Q(pk=body.get('pk'))
        return qs.filter(q)
prvdrs_list = ProviderList.as_view()


class Specials(ListView):
    model = Special
    template_name = 'specials.html'
    queryset = Special.objects.actual_specials()

    def get_queryset(self):
        qs = super(Specials, self).get_queryset()
        #TODO: refact this
        if self.request.GET:
            if self.request.GET.get('pk'):
                pk = int(self.request.GET.get('pk'))
                if pk == 1:
                    return qs.exclude(services__in=(2,3)) #inet
                elif pk==2:
                    return qs.filter(services=2).exclude(services__in=(3,)) #inet+tv
                elif pk==3:
                    return qs.filter(services=3) # inet+tv+phone
        return qs
specials = Specials.as_view()

providers/templates/providers.html
{% extends 'base.html' %}

{% block news %}
<section class="news">
    <div class="contentWrapper">
        <h2>Список интернет провайдеров - Санкт-Петербург</h2>
        {% for prvdr in object_list %}
        <div class="providerCard">
            <div class="providerLogo">
                <a href="{{prvdr.get_absolute_url}}"><img src="{{prvdr.adaptive_logo_url}}" alt="{{prvdr.title}}"></a>
            </div>
            <div class="providerResume">
                <h3>{{prvdr.title}}</h3>
                <div class="providerServices">
                    {% for srvs in prvdr.services.all %}
                    <img src="{{STATIC_PREFIX}}images/design/{{srvs.tp}}" alt="{{srvs.title}}">
                    {% endfor %}
                </div>
                <div class="providerContactRow">
                    {#{prvdr.desc|safe}#}
                </div>
                <div class="providerResumeLinks">
                    <a href="#actions">Акции</a>
                    <a href="#tarifs">Тарифы</a>
                    <a href="{% url 'reviews:reviews_list' %}?provider={{prvdr.pk}}">Отзывы</a>
                    <a href="#about">О компании</a>
                </div>
                <div class="providerDescriptionsTabs">
                    <div class="providerDescriptionsTab providerDescription">
                        <h3>{{prvdr.title}}</h3>
                        {{prvdr.desc|safe}}
                    </div>
                    <div class="providerDescriptionsTab providerTarifes">
                        {% if prvdr.tariffs.internet %}
                        <ul class="providersList">
                            {% for tariff in prvdr.tariffs.internet %}
                                {% include 'partial/provider_tariff.html' with tariff=tariff prvdr=prvdr %}
                            {% endfor %}
                        </ul>
                        {% endif %}

                        {% if prvdr.tariffs.internet_tv %}
                        <ul class="providersList">
                            {% for tariff in prvdr.tariffs.internet_tv %}
                                {% include 'partial/provider_tariff.html' with tariff=tariff prvdr=prvdr %}
                            {% endfor %}
                        </ul>
                        {% endif %}

                        {% if prvdr.tariffs.internet_phone_tv %}
                        <ul class="providersList">
                            {% for tariff in prvdr.tariffs.internet_phone_tv %}
                                {% include 'partial/provider_tariff.html' with tariff=tariff prvdr=prvdr %}
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                    <div class="providerDescriptionsTab providerActions">
                        <ul class="providersList">
                            {% for special in prvdr.specials.actual_specials %}
                            <li class="providerRow">
                                <div class="providerLeftPart">
                                    <time class="actionTime">{{special.start_date}}</time><br>
                                    <div class="tarifName"><h3><a href="{{special.get_absolute_url}}">{{special.title}}</a></h3></div>
                                    <div class="tarifDescription">{{special.desc|safe}}</div>
                                </div>
                                <div class="providerRightPart">
                                    {% if special.tariffs %}
                                    <p class="price">{{special.tariffs.price}} руб/мес</p>
                                    <a href="{% url 'order' %}?prvdr={{prvdr.pk}}&tariff={{special.tariffs.pk}}" class="button">Подключить</a>
                                    {% endif %}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="providerRating">
                <div class="providerRatingTitle">Рейтинг:</div>
                <div class="providerRatingCounter">{{prvdr.rating|default:'-'}}</div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

providers/templates/specials.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block news %}
<section class="news">
    <div class="contentWrapper">
        <h2>Акции интернет провайдеров - Санкт-Петербург</h2>
        <ul class="providersList">
            {% for special in object_list %}
            <li class="providerRow">
                <div class="providerLogo">
                    {% for provider in special.provider_set.all %}
                    <a href="{{provider.get_absolute_url}}"><img src="{{provider.logo_120_url}}" alt="{{provider.title}}"></a>
                    {% endfor %}
                </div>
                <div class="providerLeftPart">
                    <time class="actionTime">{{special.start_date}}</time><br>
                    <div class="tarifName">{{special.title}}</div>
                    <div class="tarifDescription">{{special.desc|safe}}</div>
                </div>
                <div class="providerRightPart">
                    {% if special.tariffs %}
                    <p class="price"><b>{{special.tariffs.price}}</b> руб/мес</p>
                    <a href="{% url 'order' %}?prvdr={{prvdr.pk}}&tariff={{special.tariffs.pk}}" class="button">Подключить</a>
                    {% endif %}
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}