base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('base.views',
    url(r'^flatpages/(?P<slug>.*)/$', 'flat_page', name='flat_page'),
)

reviews/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('reviews.views',
    url(r'^review_create/$', 'review_create', name='review_create'),
    url(r'^reviews_list/$', 'reviews_list', name='reviews_list'),
)

spbisp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^captcha/', include('captcha.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^admin/address/update_from_csv/',
        'address.views.update_addresses',
        name='update_addresses'
    ),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^providers/', include('providers.urls', namespace='providers')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns+= patterns('base.views',
    url(r'^$', 'index', name='index'),
    url(r'^order/$', 'order', name='order'),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
#coding: utf-8
from django.db import models

from providers.models import Provider

from .managers import ReviewsManager


class Review(models.Model):
    objects=ReviewsManager()
    name = models.CharField(u'Имя', max_length=255)
    text = models.TextField(u'Текст сообщения', max_length=4096)
    rate = models.PositiveSmallIntegerField(u'Оценка', default=5)
    moderation = models.BooleanField('Опубликовать', default=False)
    added = models.DateTimeField(auto_now_add=True)
    provider = models.ForeignKey(Provider,
                                verbose_name=Provider._meta.verbose_name)
    __unicode__ = lambda self: self.name
    class Meta:
        ordering = '-added', 'moderation', 'provider'
        verbose_name=u'Отзыв'
        verbose_name_plural=u'Отзывы'

reviews/forms.py
#coding: utf-8
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('name', 'text', 'rate', 'provider')

reviews/views.py
#coding: utf-8
from django.db.models import Q
from django.views.generic import ListView

from rest_framework import generics

from .forms import ReviewForm
from .models import Review


class OrderCreate(generics.CreateAPIView):
    model = Review
review_create = OrderCreate.as_view()


class RewiesList(ListView):
    model = Review
    queryset = model.objects.filter(moderation=True)
    template_name = 'reviews.html'

    def get_context_data(self, **kwargs):
        ctx = super(RewiesList, self).get_context_data(**kwargs)
        ctx['review_form'] = ReviewForm()
        return ctx

    def get_queryset(self):
        qs = super(RewiesList, self).get_queryset()
        #TODO: refact this
        q=Q()
        if self.request.GET:
            body = self.request.GET
            if body.get('provider'):
                q&=Q(provider=body.get('provider'))
        return qs.filter(q)
reviews_list = RewiesList.as_view()

reviews/templates/reviews.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block news %}
<section class="news">
    <div class="contentWrapper">
        <h2>Отзывы пользователей о провайдерах - Санкт-Петербург</h2>
        {% comment %}
        <div class="rightTops">
            <h3>Топ обсуждаемых</h3>
            <a href="#" class="rightTopItem">
                <p class="rightTopItemTitle">Beeline</p>
                <img src="images/design/logo-beeline_96x96_2.png" alt="beeline">
                <div class="providerRating">
                    <div class="providerRatingTitle">Рейтинг:</div>
                    <div class="providerRatingCounter">4,8</div>
                </div>
            </a>
            <a href="#" class="rightTopItem">
                <p class="rightTopItemTitle">skynet</p>
                <img src="images/design/logo-skynet-96x96.png" alt="skynet">
                <div class="providerRating">
                    <div class="providerRatingTitle">Рейтинг:</div>
                    <div class="providerRatingCounter">4,7</div>
                </div>
            </a>
            <a href="#" class="rightTopItem">
                <p class="rightTopItemTitle">WestCall</p>
                <img src="images/design/logo-westcall-95x95.png" alt="WestCall">
                <div class="providerRating">
                    <div class="providerRatingTitle">Рейтинг:</div>
                    <div class="providerRatingCounter">4,8</div>
                </div>
            </a>
        </div>
        {% endcomment %}
        {% for review in object_list %}
        <div class="commentCard">
            <div class="providerLogo">
                <a href="{{review.provider.get_absolute_url}}"><img src="{{review.provider.adaptive_logo_url}}" alt="{{review.provider.title}}"></a>
            </div>
            <div class="commentPart">
                <div class="starRating">
                    <div class="rating{{review.rate}}"></div>
                </div>
                <div class="commentInfo">
                    <span class="commentAuthor">{{review.name}}</span>
                    <time>{{review.added}}</time>
                    {#<a href="#this"><img src="images/design/icon-link.png" alt="ссылка на комментарий"></a>#}
                </div>
                <p>{{review.text}}</p>
                <a href="#review_form" class="addComment" prvdr="{{review.provider.id}}">+ Добавить отзыв</a>
            </div>
        </div>
        {% empty %}
        <div class="commentCard">
            <div class="commentPart">
                <p>Нет отзывов</p>
                <a href="#review_form" class="addComment" prvdr="">+ Добавить отзыв</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div style="display:none">
        <form id="review_form" class="addComment" method="post" action="">
            {% csrf_token %}
            <h3>Написать отзыв</h3>
            <div class="rateThis">
                <p id="form_invalid" class="error">Заполните все поля</p>
                <div class="starRating">
                    <div class="rating5" id="rating"></div>
                    <fieldset class="ratingField">
                        <input type="radio" name="rate" id="id_rate" value="1">
                        <input type="radio" name="rate" id="id_rate" value="2">
                        <input type="radio" name="rate" id="id_rate" value="3">
                        <input type="radio" name="rate" id="id_rate" value="4">
                        <input type="radio" name="rate" id="id_rate" value="5" checked>
                    </fieldset>
                </div>
                {% render_field review_form.name required="required" class="fancyField" placeholder="Ваше имя" %}
                {% render_field review_form.text required="required" class="fancyField" placeholder="Комментарий" %}
                {% render_field review_form.provider required="required" class="fancyField" placeholder="Провайдер" %}
                {% comment %}
                <div class="captcha">
                    <img src="/static/images/captcha.jpg" alt="Tr5nb">
                    <input type="text" name="captcha" placeholder="каптча">
                </div>
                {% endcomment %}
                <button type="submit" class="button">Написать отзыв</button>
            </div>
        </form>
    </div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $('a.addComment').fancybox({
            'scrolling': 'no',
            'titleShow': false,
            'onClosed': function() {
                $("#form_invalid").hide();
            },
            onStart: function(element) {
                $("#id_provider [value='"+$(element).attr('prvdr')+"']").attr("selected", "selected");
                console.log($(element).attr('prvdr'));
            }
        });
    });
    $(document).on('submit','#review_form', function(event) {
        event.preventDefault();
        if ($("#id_name").val().length < 1){
                $("#form_invalid").show();
                $.fancybox.resize();
            }
        $.fancybox.showActivity();
        $.ajax({
            type: "POST",
            cache: false,
            url: "{% url 'reviews:review_create' %}",
            data: $(this).serializeArray(),
            success: function(data) {
                $.fancybox('<div class="textblock">Отзыв отправлен на модерацию успешно!</div>');
            }
        });

        return false;
    });
</script>
{% endblock %}