address/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('address.views',
    url(r'^addresses/$', 'addresses', name='addresses'),
    url(r'^street_names/$', 'street_names', name='street_names'),
)

base/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('base.views',
    url(r'^flatpages/(?P<slug>.*)/$', 'flat_page', name='flat_page'),
)

orders/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('orders.views',
    url(r'^order_create/$', 'order_create', name='order_create'),
)

providers/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('providers.views',
    url(r'^prvdrs_list/$', 'prvdrs_list', name='prvdrs_list'),
    url(r'^specials/$', 'specials', name='specials'),
)

reviews/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('reviews.views',
    url(r'^review_create/$', 'review_create', name='review_create'),
    url(r'^reviews_list/$', 'reviews_list', name='reviews_list'),
)

spbisp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^captcha/', include('captcha.urls')),
    (r'^ckeditor/', include('ckeditor.urls')),

    url(r'^address/', include('address.urls', namespace='address')),
    url(r'^admin/address/update_from_csv/',
        'address.views.update_addresses',
        name='update_addresses'
    ),
    url(r'^base/', include('base.urls', namespace='base')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^providers/', include('providers.urls', namespace='providers')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
)

urlpatterns+= patterns('base.views',
    url(r'^$', 'index', name='index'),
    url(r'^order/$', 'order', name='order'),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
#coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse

from easy_thumbnails.files import get_thumbnailer
from filer.fields.image import FilerImageField

from ckeditor.fields import RichTextField


class BaseModel(models.Model):
    title = models.CharField(u'Название', max_length=255)
    __unicode__ = lambda self: self.title
    class Meta:
        abstract=True


class FlatPage(BaseModel):
    content = RichTextField(u'Содержание')
    slug = models.SlugField(u'Путь', max_length=255, unique=True,
                help_text=u'Заполнить название'
    )

    class Meta:
        verbose_name= u'простая страница'
        verbose_name_plural = u'простые страницы'

    def get_absolute_url(self):
        return reverse('base:flat_page', kwargs=dict(slug=self.slug))


class SliderItem(models.Model):
    flr_image = FilerImageField(verbose_name=u'Изображение')
    is_active = models.BooleanField(u'Показать на главной', default=True)

    @property
    def image_hd_url(self):
        opts = dict(size=(1920,1080))
        thumbnail = get_thumbnailer(self.flr_image).get_thumbnail(opts)
        return thumbnail.url

    class Meta:
        verbose_name= u'Элемент слайдера'
        verbose_name_plural = u'Элементы слайдера'


class BlockOnSlider(models.Model):
    title = models.CharField(u'Название', max_length=44)
    text = models.TextField(u'Teкст', max_length=185)
    tp = models.PositiveSmallIntegerField(u'Расположение блока', unique=True,
                            choices=(
                                        (0, u'Левый'),
                                        (1, u'Центр'),
                                        (2, u'Правый'),
                            )
    )
    __unicode__ = lambda self: self.title

    class Meta:
        verbose_name= u'Блок на слайдере'
        verbose_name_plural = u'Блоки на слайдере'


class SystemTunes(BaseModel):
    phone = models.CharField(u'Телефон', max_length=255, blank=True)
    email = models.EmailField('email', blank=True)
    is_active = models.BooleanField(u'Активный', default=True)
    sliderspeed = models.PositiveSmallIntegerField(u'Скорость слайдера, сек',
        default=10)
    google_analytics = models.TextField(u'Код Google-аналитики', blank=True)
    yandex_metrics = models.TextField(u'Код Yandex-метрики', blank=True)
    keywords = models.CharField(u'SEO keywords',
                                max_length=2048, blank=True)
    description = models.CharField(u'SEO description',
                                max_length=2048, blank=True)
    class Meta:
        verbose_name= u'Системные настройки'
        verbose_name_plural = verbose_name

    sliderspeedms = property(lambda self: self.sliderspeed*1000)

base/views.py
#coding: utf-8
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import DetailView
from django.views.generic import TemplateView

from address.models import Address
from address.views import Addresses
from providers.models import Provider

from .models import FlatPage


class IndexPage(TemplateView):
    template_name='index.html'

    def get_context_data(self, **kwargs):
        ctx = super(IndexPage, self).get_context_data(**kwargs)
        ctx['providers'] = Provider.objects.all()[:3]
        if self.request.GET:
            ctx['results'] = self.get_addrs()
        return ctx

    def get_addrs(self):
        qs = Address.objects.all()
        qs = Addresses(request=self.request).filter_queryset(qs)
        return qs
index = IndexPage.as_view()


class DetailPage(DetailView):
    template_name = 'object_detail.html'
    context_object_name = 'detail_page'
    model = FlatPage

    def get(self, request, *args, **kwargs):
        if self.get_object():
            return super(DetailPage, self).get(request, *args, **kwargs)
        else:
            return redirect(reverse('index'))
flat_page = DetailPage.as_view()


class OrderPage(TemplateView):
    template_name='order.html'
order = OrderPage.as_view()

base/templates/partial/address_order_form.html
{% load widget_tweaks %}
<section class="news">
    <div class="contentWrapper" id="address"><div id="providers"></div></div>
    <div style="display:none">
        <form id="order_form">
            {% csrf_token %}
            <div class="textblock">
                <p id="form_invalid" class="error">Заполните все поля</p>
                {% render_field order_form.fio placeholder=order_form.fio.label required="required" class="fancyField" %}<br/>
                {% render_field order_form.apartment placeholder=order_form.apartment.label required="required" class="fancyField" %}<br/>
                {% render_field order_form.phone placeholder=order_form.phone.label required="required" class="fancyField" %}<br/>
                {% render_field order_form.time placeholder=order_form.time.label required="required" class="fancyField" %}<br/>
                <input type="hidden" name="address" value="" id="id_address">
                <input type="hidden" name="provider" value="" id="id_provider">
                <input type="hidden" name="tariff" value="" id="id_tariff">
                <button type="submit" class="button">Подключить</button>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        $(document).ready(function() {
            $('form.searchForm').on("submit", function(event){
                event.preventDefault();
                var params = $(this).serialize();
                if (params) {
                    get_providers_data(params);
                }
                return false;
            });

            function get_providers_data(params) {
                var url = '{% url 'address:addresses' %}?search=1'
                if (params) {
                    url = url + '&' + params;
                }
                if ($.urlParam('prvdr')) {
                    url=url+'&prvdr='+$.urlParam('prvdr');
                }
                $.ajax({
                    url: url,
                    success: function( data ) {
                        $("#providers").remove();
                        if (data.length > 0) {
                            $('#address').append('<div id=\"providers\"></div>');
                            $('#providers').append($('form#order_form'));
                            $('form#order_form input[name=tariff]').val($.urlParam('tariff'));
                            $('form#order_form input[name=provider]').val($.urlParam('prvdr'));
                            $('form#order_form input[name=address]').val(data[0].id);
                        }
                        else {
                            $('#address').append('<div id=\"providers\"><p>К сожалению, данный провайдер не подключает по вашему адресу.</p><p><a href=\"/?'+params+'\" id=\"others\">Посмотреть других провайдеров</a></p></div>');
                        }
                    }
                });
            };
        });
    </script>

    <script type="text/javascript">
        jQuery('#id_time').datetimepicker({
              //inline:true,
              lang:'ru',
              format: 'Y-m-d H:i',
              minDate: 0,
              minTime: '9:00',
        });
        $(document).on('submit','#order_form', function(event) {
            event.preventDefault();
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'orders:order_create' %}",
                data: $(this).serializeArray(),
                success: function(data) {
                    $("#providers").remove();
                    $('#address').append('<div class="textblock">Заявка отправлена успешно!</div>');
                }
            });

            return false;
        });
    </script>
</section>

base/templates/partial/addresses.html
{% load widget_tweaks %}
<section class="news">
    <div class="contentWrapper" id="address">
        {%if results %}
        <div id="providers">
            <h2>Тарифы интернет-провайдеров</h2>
            {% for addr in results %}
            <p class="resultAdress" addressid="{{addr.id}}">По адресу: <b>{{addr.full_address}}</b></p>
            {% for prvdr in addr.providers.all %}
            <h3 providerid="{{prvdr.id}}">{{prvdr.title}}</h3>
            <ul class="providersList">
                    {% for trf in prvdr.tariffs.all %}
                    <li class="providerRow" tariffid="{{trf.id}}">
                        <div class="providerLogo">
                            <a href="{{prvdr.get_absolute_url}}"><img src="{{prvdr.logo_120_url}}" alt="{{prvdr.title}}"></a>
                        </div>
                        <div class="providerLeftPart">
                            <div class="tarifName"><b>{{trf.title}}</b></div>
                            <div class="tarifSpeed"><span>{{trf.speed}}</span></div>
                            <div class="tarifDescription">{{trf.desc|safe}}</div>
                        </div>
                        <div class="providerRightPart">
                            {% comment %}
                            <div class="providerServices">
                            {% for srv in trs.services %}
                                <img src="/static/images/design/{{srv.tp}}" alt="{{srv.title}}">
                            {%endfor%}
                            </div>
                            {% endcomment %}
                            <p class="price"><b>{{trf.price}}</b> руб/мес</p>
                            <a href="#order_form" class="button">Подключить</a>
                        </div>
                    </li>
                    {% endfor %}
            </ul>
            {% endfor %}
        </div> 
        {% endfor %}
        {% else%}
        <div id="providers"></div>
        {% endif %}
    </div>
    <div style="display:none">
        <form id="order_form">
            {% csrf_token %}
            <div class="textblock">
                <p id="form_invalid" class="error">Заполните все поля</p>
                {% render_field order_form.fio placeholder=order_form.fio.label required="required" class="fancyField" %}<br/>
                {% render_field order_form.apartment placeholder=order_form.apartment.label required="required" class="fancyField" %}<br/>
                {% render_field order_form.phone placeholder=order_form.phone.label required="required" class="fancyField" %}<br/>
                {% render_field order_form.time placeholder=order_form.time.label required="required" class="fancyField" %}<br/>
                <input type="hidden" name="address" value="" id="id_address">
                <input type="hidden" name="provider" value="" id="id_provider">
                <input type="hidden" name="tariff" value="" id="id_tariff">
                <button type="submit" class="button">Подключить</button>
            </div>
        </form>
    </div>  
    <script id="providers-template" type="text/x-handlebars-template">
        {% verbatim %}
        <div id="providers">
        <h2>Тарифы интернет-провайдеров</h2>
        {{#each results}}
        <p class="resultAdress" addressid="{{id}}">По адресу: <b>{{full_name}}</b></p>
            {{#each providers}}
                <h3 providerid="{{id}}">{{title}}</h3>
                {{#if inet_trfs}}
                <ul class="providersList">
                    {{#each inet_trfs}}
                    <li class="providerRow" tariffid="{{id}}">
                        <div class="providerLogo">
                            <a href="{{../url}}"><img src="{{../logo_120_url}}" alt="{{../title}}"></a>
                        </div>
                        <div class="providerLeftPart">
                            <div class="tarifName"><b>{{title}}</b></div>
                            <div class="tarifSpeed"><span>{{speed}}</span></div>
                            <div class="tarifDescription">{{{desc}}}</div>
                        </div>
                        <div class="providerRightPart">
                            <p class="price"><b>{{price}}</b> руб/мес</p>
                            <a href="#order_form" class="button">Подключить</a>
                        </div>
                    </li>
                    {{/each}}
                </ul>
                {{/if}}
                {{#if tv_trfs}}
                <ul class="providersList">
                    {{#each tv_trfs}}
                    <li class="providerRow" tariffid="{{id}}">
                        <div class="providerLogo">
                            <a href="{{../url}}"><img src="{{../logo_120_url}}" alt="{{../title}}"></a>
                        </div>
                        <div class="providerLeftPart">
                            <div class="tarifName"><b>{{title}}</b></div>
                            <div class="tarifSpeed"><span>{{speed}}</span></div>
                            <div class="tarifDescription">{{{desc}}}</div>
                        </div>
                        <div class="providerRightPart">
                            <p class="price"><b>{{price}}</b> руб/мес</p>
                            <a href="#order_form" class="button">Подключить</a>
                        </div>
                    </li>
                    {{/each}}
                </ul>
                {{/if}}
                {{#if phone_trfs}}
                <ul class="providersList">
                    {{#each phone_trfs}}
                    <li class="providerRow" tariffid="{{id}}">
                        <div class="providerLogo">
                            <a href="{{../url}}"><img src="{{../logo_120_url}}" alt="{{../title}}"></a>
                        </div>
                        <div class="providerLeftPart">
                            <div class="tarifName"><b>{{title}}</b></div>
                            <div class="tarifSpeed"><span>{{speed}}</span></div>
                            <div class="tarifDescription">{{{desc}}}</div>
                        </div>
                        <div class="providerRightPart">
                            <p class="price"><b>{{price}}</b> руб/мес</p>
                            <a href="#order_form" class="button">Подключить</a>
                        </div>
                    </li>
                    {{/each}}
                </ul>
                {{/if}} 
            {{/each}}
        {{/each}}
        {% endverbatim %}
        </div>
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('form.searchForm').on("submit", function(event){
                event.preventDefault();
                var params = $(this).serialize();
                if (params) {
                    get_providers_data(params);
                }
                return false;
            });

            function set_dom(address_id) {
                $('a.button').fancybox({
                    'scrolling': 'no',
                    'titleShow': false,
                    'onClosed': function() {
                        $("#form_invalid").hide();
                    }
                });
                $('a.button').on('click', function(event) {
                    var tariff = $(event.target).parent().parent();
                    var provider = tariff.parent().prev();
                    $('form#order_form input[name=tariff]').val(tariff.attr('tariffid'));
                    $('form#order_form input[name=provider]').val(provider.attr('providerid'));
                    $('form#order_form input[name=address]').val(address_id);
                });

            };

            function get_providers_data(params) {
                var url = '{% url 'address:addresses' %}?search=1'
                if (params) {
                    url = url + '&' + params;
                }
                $.ajax({
                    url: url,
                    success: function( data ) {
                        var source = $("#providers-template").html();
                        var template = Handlebars.compile(source);
                        var context = {results: data,};
                        var html = template(context);
                        $("#providers").remove();
                        $("#address").append(html);
                        set_dom(data[0].id);
                    }
                });
            };
            {%if results %}
            set_dom({{results.0.id}});
            {% endif %}
        });
    </script>

    <script type="text/javascript">
        jQuery('#id_time').datetimepicker({
              //inline:true,
              lang:'ru',
              format: 'Y-m-d H:i',
              minDate: 0,
              minTime: '9:00',
        });
        $(document).on('submit','#order_form', function(event) {
            event.preventDefault();
            if ($("#id_fio").val().length < 1){
                    $("#form_invalid").show();
                    $.fancybox.resize();
                }
            $.fancybox.showActivity();
            $.ajax({
                type: "POST",
                cache: false,
                url: "{% url 'orders:order_create' %}",
                data: $(this).serializeArray(),
                success: function(data) {
                    $.fancybox('<div class="textblock">Заявка отправлена успешно!</div>');
                }
            });

            return false;
        });
    </script>
</section>

base/templates/partial/footer.html
<footer>
    <div class="contentWrapper">
        <div class="footercopyright">
            <p>Indev Group © 2014.  All rights reserved.</p>
        </div>
        <div class="bottomNav">
            <ul class="bottomNavList">
                <li class="bottomNavItem"><a href="{% url 'index' %}">Главная</a></li>
                <li class="bottomNavItem"><a href="{% url 'providers:prvdrs_list' %}">Провайдеры</a></li>
                <li class="bottomNavItem"><a href="{% url 'providers:specials' %}">Акции</a></li>
                <li class="bottomNavItem"><a href="{% url 'base:flat_page' 'technologies' %}">Технологии</a></li>
                <li class="bottomNavItem"><a href="{% url 'reviews:reviews_list' %}">Отзывы</a></li>
                <li class="bottomNavItem"><a href="{% url 'base:flat_page' 'about_us' %}">О нас</a></li>
            </ul>
        </div>
    </div>
</footer>

base/templates/partial/head.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<meta charset="UTF-8">
<title>spb-internet group</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content=""/>
<meta name="keywords" content=""/>

<link href="{{STATIC_PREFIX}}css/jquery-ui-1.10.4.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{STATIC_PREFIX}}css/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
<link rel="stylesheet" href="{{STATIC_PREFIX}}css/jquery.datetimepicker.css" type="text/css" media="screen" />
<link href="{{STATIC_PREFIX}}css/owl.carousel.css" rel="stylesheet" type="text/css" />
<link href="{{STATIC_PREFIX}}css/owl.theme.css" rel="stylesheet" type="text/css" />
<link href="{{STATIC_PREFIX}}css/style.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:400,500,400italic,700,700italic,500italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/handlebars-v1.3.0.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery-ui-1.10.4.min.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery.datetimepicker.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/owl.carousel.min.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/jquery-scrollto.js"></script>
<script type="text/javascript" src="{{STATIC_PREFIX}}js/main.js"></script>

base/templates/partial/header.html
<header class="header">
    <div class="headerWrapper">
        <div class="logo">
            <a href="/">SPB Internet</a>
        </div>
        <div class="topNav">
            <ul class="topNavList">
                <li class="topNavItem"><a href="{% url 'index' %}">Главная</a></li>
                <li class="topNavItem"><a href="{% url 'providers:prvdrs_list' %}">Провайдеры</a></li>
                <li class="topNavItem"><a href="{% url 'providers:specials' %}">Акции</a></li>
                <li class="topNavItem"><a href="{% url 'base:flat_page' 'technologies' %}">Технологии</a></li>
                <li class="topNavItem"><a href="{% url 'reviews:reviews_list' %}">Отзывы</a></li>
                <li class="topNavItem"><a href="{% url 'base:flat_page' 'about_us' %}">О нас</a></li>
            </ul>
        </div>
    </div>
</header>

base/templates/partial/reviews.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<section class="news">
    <div class="contentWrapper">
        <h2>ПОСЛЕДНИЕ ОТЗЫВЫ</h2>
        <ul class="newsList">
            {% for provider in providers %}
            <li class="newsItem">
                <a href="{{provider.get_absolute_url}}"><img src="{{provider.adaptive_logo_url}}" alt="{{provider.title}}"></a>
                <div class="newsAnounce">
                    <span class="commentAuthor">{{provider.review_set.actual.last.name}}</span>
                    <time>{{provider.review_set.actual.last.added}}</time>
                    <p>{{provider.review_set.actual.last.text}}</p>
                </div>
                <a href="{% url 'reviews:reviews_list' %}?provider={{provider.pk}}" class="newsMore">Ещё</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>

base/templates/partial/topblock.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<section class="topBlock">
    <div class="owl-carousel owl-theme" id="partners">
        {% for slide in slider %}
        <div class="owl-item">
            <div class="bannerSlide">
                <img src="{{slide.image_hd_url}}" alt=""/>
            </div>
        </div>
        {% empty %}
        <div class="owl-item">
            <div class="bannerSlide">
                <img src="{{STATIC_PREFIX}}images/page-1_slider-1.jpg" alt=""/>
            </div>
        </div>
        <div class="owl-item">
            <div class="bannerSlide">
                <img src="{{STATIC_PREFIX}}images/page-1_slider-2.jpg" alt=""/>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="contentWrapper onSlide">
        <ul class="vectorslist">
            <li class="vectorcol">
                <div class="vectorWrapper">
                    <a href="{% url 'providers:specials' %}?pk=1"><img src="{{STATIC_PREFIX}}images/internet.png" alt="{{left_block.title}}"></a>
                    {% if left_block %}
                    <h3>{{left_block.title}}</h3>
                    <p>{{left_block.text}}</p>
                    {% else %}
                    <h3>Интернет</h3>
                    <p>Есть много вариантов Lorem Ipsum, но большинство из них имеет не всегда приемлемые модификации модификации</p>
                    {% endif %}
                </div>
            </li>
            <li class="vectorcol">
                <div class="vectorWrapper">
                    <a href="{% url 'providers:specials' %}?pk=2"><img src="{{STATIC_PREFIX}}images/internet-tv.png" alt="{{center_block.title}}"></a>
                    {% if center_block %}
                    <h3>{{center_block.title}}</h3>
                    <p>{{center_block.text}}</p>
                    {% else %}
                    <h3>Интернет + ТВ</h3>
                    <p>Есть много вариантов Lorem Ipsum, но большинство из них имеет не всегда приемлемые модификации</p>
                    {% endif %}
                </div>
            </li>
            <li class="vectorcol">
                <div class="vectorWrapper">
                    <a href="{% url 'providers:specials' %}?pk=3"><img src="{{STATIC_PREFIX}}images/internet-tv-phone.png" alt="{{right_block.title}}"></a>
                    {% if right_block %}
                    <h3>{{right_block.title}}</h3>
                    <p>{{right_block.text}}</p>
                    {% else %}
                    <h3>Интернет + ТВ + Телефония</h3>
                    <p>Есть много вариантов Lorem Ipsum, но большинство из них имеет не всегда приемлемые модификации</p>
                    {% endif %}
                </div>
            </li>
        </ul>
    </div>
</section>